### ISSUE TITLE
wrong number of arguments error when attempting to run

### ISSUE THREAD

**Issue by nwestallen** [mawise/bookshelf#1]
Hi, sorry I'm not familiar with ruby at all and I tried running `ruby app.rb "/Users/<my_username>/Calibre Library"` after a successful `bundle install` and get the following error:

```
/opt/homebrew/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/rack/handler/puma.rb:67:in `run': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1506:in `start_server'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1444:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/sinatra-1.4.8/lib/sinatra/main.rb:25:in `block in <module:Sinatra>'
```
Idk if this is a ruby version or dependency issue in my environment, but any guidance would be greatly appreciated. Running on an M1 macbook air, macOS Ventura 13.6.7

**Comment by mawise** [comment]
Huh.  I install ruby with rbenv: https://rbenv.org/

That will ensure you're using the same tiny version as i am.  I've heard of
Ruby installed with brew directly having issues with which Ruby gems get
used in the dependency chain.

**Comment by christianboyle** [comment]
I'm seeing the same as @nwestallen (but on Ubuntu 22.04):

![2024-08-13_08-53-52AM](https://github.com/user-attachments/assets/8af5fa46-4207-4750-97b2-1c6c018e5f25)

**Comment by jhbadger** [comment]
Same problem on Mac M1 (Sonoma 14.5),  using ruby 3.1.4p223 installed from rbenv. Is it an issue with puma? Has its API changed recently?

.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/puma-6.4.2/lib/rack/handler/puma.rb:67:in `run': wrong number of arguments (given 2, expected 1) (ArgumentError)

**Comment by simonf** [comment]
Same problem on Debian 12 (bookworm) using ruby 3.1.4p233 installed via rvm. I tried downgrading puma and sinatra to 6.4.1 and 1.4.7 respectively, but got the same error

**Comment by mawise** [comment]
I haven't been able to reproduce, but I was forcing an old version of sinatra and rack, which I've now updated.  Can someone on this thread try another `bundle install` and see if that fixes it?

**Comment by simonf** [comment]
Thanks for such a fast response! It's working fine now. Looks great!

**Comment by christianboyle** [comment]
@mawise Looks good now, thanks for the quick fix!

![fixed](https://github.com/user-attachments/assets/4e9c5a1b-8b2c-4904-966f-7ffcded0de5c)

**Comment by mawise** [comment]
Enjoy!
